-- Migration 0006: Major DB cleanup
-- Applied 2026-03-29
--
-- 1. Renamed revenue → transactions (dropped old empty transactions table)
-- 2. Replaced 'employee'+'customer' roles with 'security'+'retail'
-- 3. Added 'manager' to role constraint
-- 4. Fixed employee roles, pay rates, manager_ids
-- 5. Renamed Custodian dept → Retail & Operations
-- 6. Added title + description columns to events
-- 7. Fixed inventory prices and categories
-- 8. Cleaned up test data (Testo animal, Plush Cheeseburger, junk revenue)
-- 9. Updated create_zoo_user RPC for new role system
--
-- This migration was applied directly to Supabase. This file is for reference.
